[PAR-4327] admin cart balancing setting toggle
helloextend/magento-extend-integration pull request #104
Opened 2023-07-25 14:30 UTC by aarondeane-extend

# Description
- Add toggle to admin to enable/disable cart balancing
- Add backend configuration to save at a `default` level

## Ticket
https://helloextend.atlassian.net/browse/PAR-4327

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have deployed and validated my code on a sandbox
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-07-25 18:01 UTC, milesmcleod requested changes

2023-07-25 18:01 UTC, milesmcleod commented on etc/adminhtml/system.xml
> +                <field id="recreate_pp_product" type="button" sortOrder="20" showInDefault="1" canRestore="1">
i dunno what `canRestore` does for a `button` field - probably not an issue, but maybe not necessary?

2023-07-25 18:01 UTC, milesmcleod commented on etc/adminhtml/system.xml
> +                <field id="enable_cart_balancing" translate="label" type="select" sortOrder="30" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="1">
probably want the `sortOrder` of this field to be `20` if we want it pinned below the `Recreate` button

2023-07-25 18:28 UTC, aarondeane-extend commented on etc/adminhtml/system.xml
> +                <field id="enable_cart_balancing" translate="label" type="select" sortOrder="30" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="1">
I think the sortOrder resets within groups

2023-07-25 19:30 UTC, milesmcleod commented on etc/adminhtml/system.xml
> +                <field id="enable_cart_balancing" translate="label" type="select" sortOrder="30" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="1">
whoops, didn't notice that. in that case we should leave this at `30` and probably bump the `offer_display_settings` group below up to 40, right? that'd be sequential

2023-07-25 20:10 UTC, aarondeane-extend commented on etc/adminhtml/system.xml
> +                <field id="enable_cart_balancing" translate="label" type="select" sortOrder="30" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="1">
good call

2023-07-25 20:11 UTC, aarondeane-extend commented on etc/adminhtml/system.xml
> +                <field id="recreate_pp_product" type="button" sortOrder="20" showInDefault="1" canRestore="1">
from what I've read this just allows you to restore it to the default value from admin without having to manually enter it. Pretty much just copied the other implementation of this field type

2023-07-26 12:31 UTC, milesmcleod approved these changes

2023-07-26 13:45 UTC, adityaagashe1 approved these changes

2023-07-26 13:45 UTC, adityaagashe1 commented on Model/Config/Backend/Enable.php
> +            $this->writer->save(\Extend\Integration\Service\Extend::ENABLE_CART_BALANCING, 0);
By Default, we want to turn off the cartBalancing?

2023-07-26 15:08 UTC, merged