PAR-4184 Enable/Disable PP
helloextend/magento-extend-integration pull request #45
Opened 2023-05-04 16:07 UTC by scott-taylor-extend

This adds a store configuration drop down for Product Protection in our module.  This dropdown is conditional on the old product protection module being disabled, or the whole module disabled.

- If the Guidance module is enabled, and Product Protection set to Yes, then the option to enable the new Product Protection is disabled a greyed out.
- If the Guidance module is disabled, but the product protection value is set to yes in `core_config_data`, the new module is can still be enabled.
- If the Guidance module is enabled, but Product Protection is turned off, the new Product Protection can be enabled.
- If the new product protection is enabled, but product protection on the Guidance module is switched to enable, then the new product protection is automatically disabled.

## Ticket

PAR-4184
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor (new code changes but everything functions the same)

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have deployed and validated my code on a sandbox
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-05-04 20:14 UTC, milesmcleod submitted a review, later dismissed

2023-05-05 14:33 UTC, billhefty requested changes
Comments in Slack

2023-05-05 21:17 UTC, aarondeane-extend approved these changes

2023-05-05 21:56 UTC, billhefty approved these changes

2023-05-05 22:59 UTC, merged