chore: [PAR-4211] add bash script for linting php and xml with helpful output
helloextend/magento-extend-integration pull request #46
Opened 2023-05-04 21:49 UTC by milesmcleod

# Description

new bash script that works around the fact that the prettier CLI does not include any verbose or diff-related options to show you what it actually wants you to change

## Ticket

https://helloextend.atlassian.net/browse/PAR-4211

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor (new code changes but everything functions the same)

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have deployed and validated my code on a sandbox
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-05-04 22:41 UTC, jomarsantos submitted a review, later dismissed

2023-05-05 13:51 UTC, billhefty commented on scripts/lint-and-display-diff.sh
> +echo -e "fix all files: 'git diff --diff-filter=ACMRTUXB --name-only origin/master | grep -E \"(.$1$)\" | xargs npx prettier --parser=$1 --write'"
```suggestion
echo -e "fix all files: 'git diff --diff-filter=ACMRTUXB --name-only origin/master | grep -E \"(.$1$)\" | xargs prettier --parser=$1 --write'"
```

If `prettier` is installed as a dev dependency already we can use that specific version to avoid any breaking changes with `npx` pulling the latest right? Unsure if this would need to be updated to find the absolute path of `prettier` in `node_modules`.

2023-05-05 14:01 UTC, billhefty approved these changes
Previous comment not a blocker

2023-05-05 15:16 UTC, billhefty requested changes
Comments in slack

2023-05-05 17:05 UTC, milesmcleod commented on scripts/lint-and-display-diff.sh
> +echo -e "fix all files: 'git diff --diff-filter=ACMRTUXB --name-only origin/master | grep -E \"(.$1$)\" | xargs npx prettier --parser=$1 --write'"
swapped out `npx` in favor of `yarn`

2023-05-05 17:15 UTC, billhefty approved these changes

2023-05-05 17:18 UTC, jomarsantos approved these changes

2023-05-05 17:18 UTC, merged